analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.3460515760816634
color:
  saturation: 0.8381812553852797
  brandStrength: 0.4984216331504285
  rhythmicContrast: 0.233149582054466
  brandColors:
    - '#040204'
    - '#E0DFE1'
    - '#77180B'
    - '#544C5B'
    - '#FBCF39'
  lightness: 0.5742263766005635
purpose: []
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: RKBA
typography_spectrum: 0.2578971537295729
